import { NextRequest, NextResponse } from 'next/server';
import { sql } from '@vercel/postgres';

export async function GET() {
    try {
        const result = await sql`
            SELECT * FROM student_profiles 
            ORDER BY created_at DESC
        `;
        return NextResponse.json(result.rows);
    } catch (error) {
        console.error('Failed to fetch profiles:', error);
        return NextResponse.json(
            { error: 'Failed to fetch profiles' },
            { status: 500 }
        );
    }
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const {
            student_id,
            // 生徒基本情報
            student_last_name,
            student_first_name,
            student_last_name_kana,
            student_first_name_kana,
            gender,
            birth_date,
            registered_address,
            // 生徒現在住所
            student_postal_code,
            student_address,
            student_address_detail,
            student_phone,
            // 出身校情報
            middle_school_name,
            graduation_date,
            // 保護者1情報
            guardian1_last_name,
            guardian1_first_name,
            guardian1_last_name_kana,
            guardian1_first_name_kana,
            guardian1_postal_code,
            guardian1_address,
            guardian1_address_detail,
            guardian1_phone,
            guardian1_relationship,
            guardian1_relationship_other,
            guardian1_email,
            guardian1_workplace_name,
            guardian1_workplace_postal_code,
            guardian1_workplace_address,
            guardian1_workplace_address_detail,
            guardian1_workplace_phone,
            // 保護者2情報
            guardian2_last_name,
            guardian2_first_name,
            guardian2_last_name_kana,
            guardian2_first_name_kana,
            guardian2_postal_code,
            guardian2_address,
            guardian2_address_detail,
            guardian2_phone,
            guardian2_relationship,
            guardian2_relationship_other,
            guardian2_email,
            // 書類送付先
            document_recipient_last_name,
            document_recipient_first_name,
            document_recipient_postal_code,
            document_recipient_address,
            document_recipient_address_detail,
            // 緊急連絡先
            emergency1_last_name,
            emergency1_first_name,
            emergency1_phone,
            emergency1_relationship,
            emergency1_relationship_other,
            emergency2_last_name,
            emergency2_first_name,
            emergency2_phone,
            emergency2_relationship,
            emergency2_relationship_other,
            // 兄弟姉妹情報
            has_siblings_at_school,
            // 家族情報
            family1_last_name,
            family1_first_name,
            family1_relationship,
            family1_relationship_other,
            family1_birth_date,
            family1_living_status,
            family1_workplace_school,
            family2_last_name,
            family2_first_name,
            family2_relationship,
            family2_relationship_other,
            family2_birth_date,
            family2_living_status,
            family2_workplace_school,
            family3_last_name,
            family3_first_name,
            family3_relationship,
            family3_relationship_other,
            family3_birth_date,
            family3_living_status,
            family3_workplace_school,
            family4_last_name,
            family4_first_name,
            family4_relationship,
            family4_relationship_other,
            family4_birth_date,
            family4_living_status,
            family4_workplace_school,
            family5_last_name,
            family5_first_name,
            family5_relationship,
            family5_relationship_other,
            family5_birth_date,
            family5_living_status,
            family5_workplace_school,
            family6_last_name,
            family6_first_name,
            family6_relationship,
            family6_relationship_other,
            family6_birth_date,
            family6_living_status,
            family6_workplace_school,
            // 通学方法
            commute_method,
            jr_start,
            jr_end,
            subway_nishin_start,
            subway_nishin_end,
            subway_kaigan_start,
            subway_kaigan_end,
            hankyu_start,
            hankyu_end,
            kobe_electric_start,
            kobe_electric_end,
            hanshin_start,
            hanshin_end,
            sanyo_start,
            sanyo_end,
            kobe_bus_start,
            kobe_bus_end,
            sanyo_bus_start,
            sanyo_bus_end,
            shinhi_bus_start,
            shinhi_bus_end,
            other1_transport,
            other1_start,
            other1_end,
            other2_transport,
            other2_start,
            other2_end,
            via_station,
            // 芸術科目選択
            art_first_choice,
            art_second_choice,
            // 持病・健康情報
            has_chronic_illness,
            accommodation_notes,
            family_communication,
            chronic_illness_details,
            // フォーム進捗状況
            personal_info_completed,
            commute_info_completed,
            art_selection_completed,
            health_info_completed
        } = body;

        const result = await sql`
            INSERT INTO student_profiles (
                student_id,
                student_last_name, student_first_name, student_last_name_kana, student_first_name_kana,
                gender, birth_date, registered_address,
                student_postal_code, student_address, student_address_detail, student_phone,
                middle_school_name, graduation_date,
                guardian1_last_name, guardian1_first_name, guardian1_last_name_kana, guardian1_first_name_kana,
                guardian1_postal_code, guardian1_address, guardian1_address_detail, guardian1_phone,
                guardian1_relationship, guardian1_relationship_other, guardian1_email,
                guardian1_workplace_name, guardian1_workplace_postal_code, guardian1_workplace_address,
                guardian1_workplace_address_detail, guardian1_workplace_phone,
                guardian2_last_name, guardian2_first_name, guardian2_last_name_kana, guardian2_first_name_kana,
                guardian2_postal_code, guardian2_address, guardian2_address_detail, guardian2_phone,
                guardian2_relationship, guardian2_relationship_other, guardian2_email,
                document_recipient_last_name, document_recipient_first_name, document_recipient_postal_code,
                document_recipient_address, document_recipient_address_detail,
                emergency1_last_name, emergency1_first_name, emergency1_phone, emergency1_relationship, emergency1_relationship_other,
                emergency2_last_name, emergency2_first_name, emergency2_phone, emergency2_relationship, emergency2_relationship_other,
                has_siblings_at_school,
                family1_last_name, family1_first_name, family1_relationship, family1_relationship_other,
                family1_birth_date, family1_living_status, family1_workplace_school,
                family2_last_name, family2_first_name, family2_relationship, family2_relationship_other,
                family2_birth_date, family2_living_status, family2_workplace_school,
                family3_last_name, family3_first_name, family3_relationship, family3_relationship_other,
                family3_birth_date, family3_living_status, family3_workplace_school,
                family4_last_name, family4_first_name, family4_relationship, family4_relationship_other,
                family4_birth_date, family4_living_status, family4_workplace_school,
                family5_last_name, family5_first_name, family5_relationship, family5_relationship_other,
                family5_birth_date, family5_living_status, family5_workplace_school,
                family6_last_name, family6_first_name, family6_relationship, family6_relationship_other,
                family6_birth_date, family6_living_status, family6_workplace_school,
                commute_method, jr_start, jr_end, subway_nishin_start, subway_nishin_end,
                subway_kaigan_start, subway_kaigan_end, hankyu_start, hankyu_end,
                kobe_electric_start, kobe_electric_end, hanshin_start, hanshin_end,
                sanyo_start, sanyo_end, kobe_bus_start, kobe_bus_end, sanyo_bus_start, sanyo_bus_end,
                shinhi_bus_start, shinhi_bus_end, other1_transport, other1_start, other1_end,
                other2_transport, other2_start, other2_end, via_station,
                art_first_choice, art_second_choice,
                has_chronic_illness, accommodation_notes, family_communication, chronic_illness_details,
                personal_info_completed, commute_info_completed, art_selection_completed, health_info_completed
            ) VALUES (
                ${student_id},
                ${student_last_name}, ${student_first_name}, ${student_last_name_kana}, ${student_first_name_kana},
                ${gender}, ${birth_date}, ${registered_address},
                ${student_postal_code}, ${student_address}, ${student_address_detail}, ${student_phone},
                ${middle_school_name}, ${graduation_date},
                ${guardian1_last_name}, ${guardian1_first_name}, ${guardian1_last_name_kana}, ${guardian1_first_name_kana},
                ${guardian1_postal_code}, ${guardian1_address}, ${guardian1_address_detail}, ${guardian1_phone},
                ${guardian1_relationship}, ${guardian1_relationship_other}, ${guardian1_email},
                ${guardian1_workplace_name}, ${guardian1_workplace_postal_code}, ${guardian1_workplace_address},
                ${guardian1_workplace_address_detail}, ${guardian1_workplace_phone},
                ${guardian2_last_name}, ${guardian2_first_name}, ${guardian2_last_name_kana}, ${guardian2_first_name_kana},
                ${guardian2_postal_code}, ${guardian2_address}, ${guardian2_address_detail}, ${guardian2_phone},
                ${guardian2_relationship}, ${guardian2_relationship_other}, ${guardian2_email},
                ${document_recipient_last_name}, ${document_recipient_first_name}, ${document_recipient_postal_code},
                ${document_recipient_address}, ${document_recipient_address_detail},
                ${emergency1_last_name}, ${emergency1_first_name}, ${emergency1_phone}, ${emergency1_relationship}, ${emergency1_relationship_other},
                ${emergency2_last_name}, ${emergency2_first_name}, ${emergency2_phone}, ${emergency2_relationship}, ${emergency2_relationship_other},
                ${has_siblings_at_school},
                ${family1_last_name}, ${family1_first_name}, ${family1_relationship}, ${family1_relationship_other},
                ${family1_birth_date}, ${family1_living_status}, ${family1_workplace_school},
                ${family2_last_name}, ${family2_first_name}, ${family2_relationship}, ${family2_relationship_other},
                ${family2_birth_date}, ${family2_living_status}, ${family2_workplace_school},
                ${family3_last_name}, ${family3_first_name}, ${family3_relationship}, ${family3_relationship_other},
                ${family3_birth_date}, ${family3_living_status}, ${family3_workplace_school},
                ${family4_last_name}, ${family4_first_name}, ${family4_relationship}, ${family4_relationship_other},
                ${family4_birth_date}, ${family4_living_status}, ${family4_workplace_school},
                ${family5_last_name}, ${family5_first_name}, ${family5_relationship}, ${family5_relationship_other},
                ${family5_birth_date}, ${family5_living_status}, ${family5_workplace_school},
                ${family6_last_name}, ${family6_first_name}, ${family6_relationship}, ${family6_relationship_other},
                ${family6_birth_date}, ${family6_living_status}, ${family6_workplace_school},
                ${commute_method}, ${jr_start}, ${jr_end}, ${subway_nishin_start}, ${subway_nishin_end},
                ${subway_kaigan_start}, ${subway_kaigan_end}, ${hankyu_start}, ${hankyu_end},
                ${kobe_electric_start}, ${kobe_electric_end}, ${hanshin_start}, ${hanshin_end},
                ${sanyo_start}, ${sanyo_end}, ${kobe_bus_start}, ${kobe_bus_end}, ${sanyo_bus_start}, ${sanyo_bus_end},
                ${shinhi_bus_start}, ${shinhi_bus_end}, ${other1_transport}, ${other1_start}, ${other1_end},
                ${other2_transport}, ${other2_start}, ${other2_end}, ${via_station},
                ${art_first_choice}, ${art_second_choice},
                ${has_chronic_illness}, ${accommodation_notes}, ${family_communication}, ${chronic_illness_details},
                ${personal_info_completed}, ${commute_info_completed}, ${art_selection_completed}, ${health_info_completed}
            )
            ON CONFLICT (student_id) 
            DO UPDATE SET
                student_last_name = EXCLUDED.student_last_name,
                student_first_name = EXCLUDED.student_first_name,
                student_last_name_kana = EXCLUDED.student_last_name_kana,
                student_first_name_kana = EXCLUDED.student_first_name_kana,
                gender = EXCLUDED.gender,
                birth_date = EXCLUDED.birth_date,
                registered_address = EXCLUDED.registered_address,
                student_postal_code = EXCLUDED.student_postal_code,
                student_address = EXCLUDED.student_address,
                student_address_detail = EXCLUDED.student_address_detail,
                student_phone = EXCLUDED.student_phone,
                middle_school_name = EXCLUDED.middle_school_name,
                graduation_date = EXCLUDED.graduation_date,
                guardian1_last_name = EXCLUDED.guardian1_last_name,
                guardian1_first_name = EXCLUDED.guardian1_first_name,
                guardian1_last_name_kana = EXCLUDED.guardian1_last_name_kana,
                guardian1_first_name_kana = EXCLUDED.guardian1_first_name_kana,
                guardian1_postal_code = EXCLUDED.guardian1_postal_code,
                guardian1_address = EXCLUDED.guardian1_address,
                guardian1_address_detail = EXCLUDED.guardian1_address_detail,
                guardian1_phone = EXCLUDED.guardian1_phone,
                guardian1_relationship = EXCLUDED.guardian1_relationship,
                guardian1_relationship_other = EXCLUDED.guardian1_relationship_other,
                guardian1_email = EXCLUDED.guardian1_email,
                guardian1_workplace_name = EXCLUDED.guardian1_workplace_name,
                guardian1_workplace_postal_code = EXCLUDED.guardian1_workplace_postal_code,
                guardian1_workplace_address = EXCLUDED.guardian1_workplace_address,
                guardian1_workplace_address_detail = EXCLUDED.guardian1_workplace_address_detail,
                guardian1_workplace_phone = EXCLUDED.guardian1_workplace_phone,
                guardian2_last_name = EXCLUDED.guardian2_last_name,
                guardian2_first_name = EXCLUDED.guardian2_first_name,
                guardian2_last_name_kana = EXCLUDED.guardian2_last_name_kana,
                guardian2_first_name_kana = EXCLUDED.guardian2_first_name_kana,
                guardian2_postal_code = EXCLUDED.guardian2_postal_code,
                guardian2_address = EXCLUDED.guardian2_address,
                guardian2_address_detail = EXCLUDED.guardian2_address_detail,
                guardian2_phone = EXCLUDED.guardian2_phone,
                guardian2_relationship = EXCLUDED.guardian2_relationship,
                guardian2_relationship_other = EXCLUDED.guardian2_relationship_other,
                guardian2_email = EXCLUDED.guardian2_email,
                document_recipient_last_name = EXCLUDED.document_recipient_last_name,
                document_recipient_first_name = EXCLUDED.document_recipient_first_name,
                document_recipient_postal_code = EXCLUDED.document_recipient_postal_code,
                document_recipient_address = EXCLUDED.document_recipient_address,
                document_recipient_address_detail = EXCLUDED.document_recipient_address_detail,
                emergency1_last_name = EXCLUDED.emergency1_last_name,
                emergency1_first_name = EXCLUDED.emergency1_first_name,
                emergency1_phone = EXCLUDED.emergency1_phone,
                emergency1_relationship = EXCLUDED.emergency1_relationship,
                emergency1_relationship_other = EXCLUDED.emergency1_relationship_other,
                emergency2_last_name = EXCLUDED.emergency2_last_name,
                emergency2_first_name = EXCLUDED.emergency2_first_name,
                emergency2_phone = EXCLUDED.emergency2_phone,
                emergency2_relationship = EXCLUDED.emergency2_relationship,
                emergency2_relationship_other = EXCLUDED.emergency2_relationship_other,
                has_siblings_at_school = EXCLUDED.has_siblings_at_school,
                family1_last_name = EXCLUDED.family1_last_name,
                family1_first_name = EXCLUDED.family1_first_name,
                family1_relationship = EXCLUDED.family1_relationship,
                family1_relationship_other = EXCLUDED.family1_relationship_other,
                family1_birth_date = EXCLUDED.family1_birth_date,
                family1_living_status = EXCLUDED.family1_living_status,
                family1_workplace_school = EXCLUDED.family1_workplace_school,
                family2_last_name = EXCLUDED.family2_last_name,
                family2_first_name = EXCLUDED.family2_first_name,
                family2_relationship = EXCLUDED.family2_relationship,
                family2_relationship_other = EXCLUDED.family2_relationship_other,
                family2_birth_date = EXCLUDED.family2_birth_date,
                family2_living_status = EXCLUDED.family2_living_status,
                family2_workplace_school = EXCLUDED.family2_workplace_school,
                family3_last_name = EXCLUDED.family3_last_name,
                family3_first_name = EXCLUDED.family3_first_name,
                family3_relationship = EXCLUDED.family3_relationship,
                family3_relationship_other = EXCLUDED.family3_relationship_other,
                family3_birth_date = EXCLUDED.family3_birth_date,
                family3_living_status = EXCLUDED.family3_living_status,
                family3_workplace_school = EXCLUDED.family3_workplace_school,
                family4_last_name = EXCLUDED.family4_last_name,
                family4_first_name = EXCLUDED.family4_first_name,
                family4_relationship = EXCLUDED.family4_relationship,
                family4_relationship_other = EXCLUDED.family4_relationship_other,
                family4_birth_date = EXCLUDED.family4_birth_date,
                family4_living_status = EXCLUDED.family4_living_status,
                family4_workplace_school = EXCLUDED.family4_workplace_school,
                family5_last_name = EXCLUDED.family5_last_name,
                family5_first_name = EXCLUDED.family5_first_name,
                family5_relationship = EXCLUDED.family5_relationship,
                family5_relationship_other = EXCLUDED.family5_relationship_other,
                family5_birth_date = EXCLUDED.family5_birth_date,
                family5_living_status = EXCLUDED.family5_living_status,
                family5_workplace_school = EXCLUDED.family5_workplace_school,
                family6_last_name = EXCLUDED.family6_last_name,
                family6_first_name = EXCLUDED.family6_first_name,
                family6_relationship = EXCLUDED.family6_relationship,
                family6_relationship_other = EXCLUDED.family6_relationship_other,
                family6_birth_date = EXCLUDED.family6_birth_date,
                family6_living_status = EXCLUDED.family6_living_status,
                family6_workplace_school = EXCLUDED.family6_workplace_school,
                commute_method = EXCLUDED.commute_method,
                jr_start = EXCLUDED.jr_start,
                jr_end = EXCLUDED.jr_end,
                subway_nishin_start = EXCLUDED.subway_nishin_start,
                subway_nishin_end = EXCLUDED.subway_nishin_end,
                subway_kaigan_start = EXCLUDED.subway_kaigan_start,
                subway_kaigan_end = EXCLUDED.subway_kaigan_end,
                hankyu_start = EXCLUDED.hankyu_start,
                hankyu_end = EXCLUDED.hankyu_end,
                kobe_electric_start = EXCLUDED.kobe_electric_start,
                kobe_electric_end = EXCLUDED.kobe_electric_end,
                hanshin_start = EXCLUDED.hanshin_start,
                hanshin_end = EXCLUDED.hanshin_end,
                sanyo_start = EXCLUDED.sanyo_start,
                sanyo_end = EXCLUDED.sanyo_end,
                kobe_bus_start = EXCLUDED.kobe_bus_start,
                kobe_bus_end = EXCLUDED.kobe_bus_end,
                sanyo_bus_start = EXCLUDED.sanyo_bus_start,
                sanyo_bus_end = EXCLUDED.sanyo_bus_end,
                shinhi_bus_start = EXCLUDED.shinhi_bus_start,
                shinhi_bus_end = EXCLUDED.shinhi_bus_end,
                other1_transport = EXCLUDED.other1_transport,
                other1_start = EXCLUDED.other1_start,
                other1_end = EXCLUDED.other1_end,
                other2_transport = EXCLUDED.other2_transport,
                other2_start = EXCLUDED.other2_start,
                other2_end = EXCLUDED.other2_end,
                via_station = EXCLUDED.via_station,
                art_first_choice = EXCLUDED.art_first_choice,
                art_second_choice = EXCLUDED.art_second_choice,
                has_chronic_illness = EXCLUDED.has_chronic_illness,
                accommodation_notes = EXCLUDED.accommodation_notes,
                family_communication = EXCLUDED.family_communication,
                chronic_illness_details = EXCLUDED.chronic_illness_details,
                personal_info_completed = EXCLUDED.personal_info_completed,
                commute_info_completed = EXCLUDED.commute_info_completed,
                art_selection_completed = EXCLUDED.art_selection_completed,
                health_info_completed = EXCLUDED.health_info_completed,
                updated_at = NOW()
            RETURNING *
        `;

        return NextResponse.json(result.rows[0]);
    } catch (error) {
        console.error('Failed to create/update profile:', error);
        return NextResponse.json(
            { error: 'Failed to create/update profile' },
            { status: 500 }
        );
    }
}
