import { NextRequest, NextResponse } from 'next/server';
import { sql } from '@vercel/postgres';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { student_id, ...profileData } = body;

        if (!student_id) {
            return NextResponse.json(
                { error: '学生IDが必要です' },
                { status: 400 }
            );
        }

        // 既存のプロフィールを確認
        const existingProfile = await sql`
            SELECT id FROM student_profiles WHERE student_id = ${student_id}
        `;

        if (existingProfile.rows.length > 0) {
            // 更新
            const result = await sql`
                UPDATE student_profiles 
                SET 
                    student_last_name = ${profileData.student_last_name || null},
                    student_first_name = ${profileData.student_first_name || null},
                    student_last_name_kana = ${profileData.student_last_name_kana || null},
                    student_first_name_kana = ${profileData.student_first_name_kana || null},
                    gender = ${profileData.gender || null},
                    birth_date = ${profileData.birth_date || null},
                    registered_address = ${profileData.registered_address || null},
                    student_postal_code = ${profileData.student_postal_code || null},
                    student_address = ${profileData.student_address || null},
                    student_address_detail = ${profileData.student_address_detail || null},
                    student_phone = ${profileData.student_phone || null},
                    middle_school_name = ${profileData.middle_school_name || null},
                    graduation_date = ${profileData.graduation_date || null},
                    guardian1_last_name = ${profileData.guardian1_last_name || null},
                    guardian1_first_name = ${profileData.guardian1_first_name || null},
                    guardian1_last_name_kana = ${profileData.guardian1_last_name_kana || null},
                    guardian1_first_name_kana = ${profileData.guardian1_first_name_kana || null},
                    guardian1_postal_code = ${profileData.guardian1_postal_code || null},
                    guardian1_address = ${profileData.guardian1_address || null},
                    guardian1_address_detail = ${profileData.guardian1_address_detail || null},
                    guardian1_phone = ${profileData.guardian1_phone || null},
                    guardian1_relationship = ${profileData.guardian1_relationship || null},
                    guardian1_relationship_other = ${profileData.guardian1_relationship_other || null},
                    guardian1_email = ${profileData.guardian1_email || null},
                    guardian1_workplace_name = ${profileData.guardian1_workplace_name || null},
                    guardian1_workplace_postal_code = ${profileData.guardian1_workplace_postal_code || null},
                    guardian1_workplace_address = ${profileData.guardian1_workplace_address || null},
                    guardian1_workplace_address_detail = ${profileData.guardian1_workplace_address_detail || null},
                    guardian1_workplace_phone = ${profileData.guardian1_workplace_phone || null},
                    guardian2_last_name = ${profileData.guardian2_last_name || null},
                    guardian2_first_name = ${profileData.guardian2_first_name || null},
                    guardian2_last_name_kana = ${profileData.guardian2_last_name_kana || null},
                    guardian2_first_name_kana = ${profileData.guardian2_first_name_kana || null},
                    guardian2_postal_code = ${profileData.guardian2_postal_code || null},
                    guardian2_address = ${profileData.guardian2_address || null},
                    guardian2_address_detail = ${profileData.guardian2_address_detail || null},
                    guardian2_phone = ${profileData.guardian2_phone || null},
                    guardian2_relationship = ${profileData.guardian2_relationship || null},
                    guardian2_relationship_other = ${profileData.guardian2_relationship_other || null},
                    guardian2_email = ${profileData.guardian2_email || null},
                    document_recipient_last_name = ${profileData.document_recipient_last_name || null},
                    document_recipient_first_name = ${profileData.document_recipient_first_name || null},
                    document_recipient_postal_code = ${profileData.document_recipient_postal_code || null},
                    document_recipient_address = ${profileData.document_recipient_address || null},
                    document_recipient_address_detail = ${profileData.document_recipient_address_detail || null},
                    emergency1_last_name = ${profileData.emergency1_last_name || null},
                    emergency1_first_name = ${profileData.emergency1_first_name || null},
                    emergency1_phone = ${profileData.emergency1_phone || null},
                    emergency1_relationship = ${profileData.emergency1_relationship || null},
                    emergency1_relationship_other = ${profileData.emergency1_relationship_other || null},
                    emergency2_last_name = ${profileData.emergency2_last_name || null},
                    emergency2_first_name = ${profileData.emergency2_first_name || null},
                    emergency2_phone = ${profileData.emergency2_phone || null},
                    emergency2_relationship = ${profileData.emergency2_relationship || null},
                    emergency2_relationship_other = ${profileData.emergency2_relationship_other || null},
                    has_siblings_at_school = ${profileData.has_siblings_at_school || false},
                    family1_last_name = ${profileData.family1_last_name || null},
                    family1_first_name = ${profileData.family1_first_name || null},
                    family1_relationship = ${profileData.family1_relationship || null},
                    family1_relationship_other = ${profileData.family1_relationship_other || null},
                    family1_birth_date = ${profileData.family1_birth_date || null},
                    family1_living_status = ${profileData.family1_living_status || null},
                    family1_workplace_school = ${profileData.family1_workplace_school || null},
                    family2_last_name = ${profileData.family2_last_name || null},
                    family2_first_name = ${profileData.family2_first_name || null},
                    family2_relationship = ${profileData.family2_relationship || null},
                    family2_relationship_other = ${profileData.family2_relationship_other || null},
                    family2_birth_date = ${profileData.family2_birth_date || null},
                    family2_living_status = ${profileData.family2_living_status || null},
                    family2_workplace_school = ${profileData.family2_workplace_school || null},
                    family3_last_name = ${profileData.family3_last_name || null},
                    family3_first_name = ${profileData.family3_first_name || null},
                    family3_relationship = ${profileData.family3_relationship || null},
                    family3_relationship_other = ${profileData.family3_relationship_other || null},
                    family3_birth_date = ${profileData.family3_birth_date || null},
                    family3_living_status = ${profileData.family3_living_status || null},
                    family3_workplace_school = ${profileData.family3_workplace_school || null},
                    family4_last_name = ${profileData.family4_last_name || null},
                    family4_first_name = ${profileData.family4_first_name || null},
                    family4_relationship = ${profileData.family4_relationship || null},
                    family4_relationship_other = ${profileData.family4_relationship_other || null},
                    family4_birth_date = ${profileData.family4_birth_date || null},
                    family4_living_status = ${profileData.family4_living_status || null},
                    family4_workplace_school = ${profileData.family4_workplace_school || null},
                    family5_last_name = ${profileData.family5_last_name || null},
                    family5_first_name = ${profileData.family5_first_name || null},
                    family5_relationship = ${profileData.family5_relationship || null},
                    family5_relationship_other = ${profileData.family5_relationship_other || null},
                    family5_birth_date = ${profileData.family5_birth_date || null},
                    family5_living_status = ${profileData.family5_living_status || null},
                    family5_workplace_school = ${profileData.family5_workplace_school || null},
                    family6_last_name = ${profileData.family6_last_name || null},
                    family6_first_name = ${profileData.family6_first_name || null},
                    family6_relationship = ${profileData.family6_relationship || null},
                    family6_relationship_other = ${profileData.family6_relationship_other || null},
                    family6_birth_date = ${profileData.family6_birth_date || null},
                    family6_living_status = ${profileData.family6_living_status || null},
                    family6_workplace_school = ${profileData.family6_workplace_school || null},
                    commute_method = ${profileData.commute_method || null},
                    jr_start = ${profileData.jr_start || null},
                    jr_end = ${profileData.jr_end || null},
                    subway_nishin_start = ${profileData.subway_nishin_start || null},
                    subway_nishin_end = ${profileData.subway_nishin_end || null},
                    subway_kaigan_start = ${profileData.subway_kaigan_start || null},
                    subway_kaigan_end = ${profileData.subway_kaigan_end || null},
                    hankyu_start = ${profileData.hankyu_start || null},
                    hankyu_end = ${profileData.hankyu_end || null},
                    kobe_electric_start = ${profileData.kobe_electric_start || null},
                    kobe_electric_end = ${profileData.kobe_electric_end || null},
                    hanshin_start = ${profileData.hanshin_start || null},
                    hanshin_end = ${profileData.hanshin_end || null},
                    sanyo_start = ${profileData.sanyo_start || null},
                    sanyo_end = ${profileData.sanyo_end || null},
                    kobe_bus_start = ${profileData.kobe_bus_start || null},
                    kobe_bus_end = ${profileData.kobe_bus_end || null},
                    sanyo_bus_start = ${profileData.sanyo_bus_start || null},
                    sanyo_bus_end = ${profileData.sanyo_bus_end || null},
                    shinhi_bus_start = ${profileData.shinhi_bus_start || null},
                    shinhi_bus_end = ${profileData.shinhi_bus_end || null},
                    other1_transport = ${profileData.other1_transport || null},
                    other1_start = ${profileData.other1_start || null},
                    other1_end = ${profileData.other1_end || null},
                    other2_transport = ${profileData.other2_transport || null},
                    other2_start = ${profileData.other2_start || null},
                    other2_end = ${profileData.other2_end || null},
                    via_station = ${profileData.via_station || null},
                    art_first_choice = ${profileData.art_first_choice || null},
                    art_second_choice = ${profileData.art_second_choice || null},
                    has_chronic_illness = ${profileData.has_chronic_illness || false},
                    accommodation_notes = ${profileData.accommodation_notes || null},
                    family_communication = ${profileData.family_communication || null},
                    chronic_illness_details = ${profileData.chronic_illness_details || null},
                    personal_info_completed = ${profileData.personal_info_completed || false},
                    commute_info_completed = ${profileData.commute_info_completed || false},
                    art_selection_completed = ${profileData.art_selection_completed || false},
                    health_info_completed = ${profileData.health_info_completed || false},
                    updated_at = NOW()
                WHERE student_id = ${student_id}
                RETURNING *
            `;
            return NextResponse.json({ 
                success: true, 
                message: 'プロフィールを更新しました',
                profile: result.rows[0]
            });
        } else {
            // 新規作成
            const result = await sql`
                INSERT INTO student_profiles (
                    student_id,
                    student_last_name,
                    student_first_name,
                    student_last_name_kana,
                    student_first_name_kana,
                    gender,
                    birth_date,
                    registered_address,
                    student_postal_code,
                    student_address,
                    student_address_detail,
                    student_phone,
                    middle_school_name,
                    graduation_date,
                    guardian1_last_name,
                    guardian1_first_name,
                    guardian1_last_name_kana,
                    guardian1_first_name_kana,
                    guardian1_postal_code,
                    guardian1_address,
                    guardian1_address_detail,
                    guardian1_phone,
                    guardian1_relationship,
                    guardian1_relationship_other,
                    guardian1_email,
                    guardian1_workplace_name,
                    guardian1_workplace_postal_code,
                    guardian1_workplace_address,
                    guardian1_workplace_address_detail,
                    guardian1_workplace_phone,
                    guardian2_last_name,
                    guardian2_first_name,
                    guardian2_last_name_kana,
                    guardian2_first_name_kana,
                    guardian2_postal_code,
                    guardian2_address,
                    guardian2_address_detail,
                    guardian2_phone,
                    guardian2_relationship,
                    guardian2_relationship_other,
                    guardian2_email,
                    document_recipient_last_name,
                    document_recipient_first_name,
                    document_recipient_postal_code,
                    document_recipient_address,
                    document_recipient_address_detail,
                    emergency1_last_name,
                    emergency1_first_name,
                    emergency1_phone,
                    emergency1_relationship,
                    emergency1_relationship_other,
                    emergency2_last_name,
                    emergency2_first_name,
                    emergency2_phone,
                    emergency2_relationship,
                    emergency2_relationship_other,
                    has_siblings_at_school,
                    family1_last_name,
                    family1_first_name,
                    family1_relationship,
                    family1_relationship_other,
                    family1_birth_date,
                    family1_living_status,
                    family1_workplace_school,
                    family2_last_name,
                    family2_first_name,
                    family2_relationship,
                    family2_relationship_other,
                    family2_birth_date,
                    family2_living_status,
                    family2_workplace_school,
                    family3_last_name,
                    family3_first_name,
                    family3_relationship,
                    family3_relationship_other,
                    family3_birth_date,
                    family3_living_status,
                    family3_workplace_school,
                    family4_last_name,
                    family4_first_name,
                    family4_relationship,
                    family4_relationship_other,
                    family4_birth_date,
                    family4_living_status,
                    family4_workplace_school,
                    family5_last_name,
                    family5_first_name,
                    family5_relationship,
                    family5_relationship_other,
                    family5_birth_date,
                    family5_living_status,
                    family5_workplace_school,
                    family6_last_name,
                    family6_first_name,
                    family6_relationship,
                    family6_relationship_other,
                    family6_birth_date,
                    family6_living_status,
                    family6_workplace_school,
                    commute_method,
                    jr_start,
                    jr_end,
                    subway_nishin_start,
                    subway_nishin_end,
                    subway_kaigan_start,
                    subway_kaigan_end,
                    hankyu_start,
                    hankyu_end,
                    kobe_electric_start,
                    kobe_electric_end,
                    hanshin_start,
                    hanshin_end,
                    sanyo_start,
                    sanyo_end,
                    kobe_bus_start,
                    kobe_bus_end,
                    sanyo_bus_start,
                    sanyo_bus_end,
                    shinhi_bus_start,
                    shinhi_bus_end,
                    other1_transport,
                    other1_start,
                    other1_end,
                    other2_transport,
                    other2_start,
                    other2_end,
                    via_station,
                    art_first_choice,
                    art_second_choice,
                    has_chronic_illness,
                    accommodation_notes,
                    family_communication,
                    chronic_illness_details,
                    personal_info_completed,
                    commute_info_completed,
                    art_selection_completed,
                    health_info_completed
                ) VALUES (
                    ${student_id},
                    ${profileData.student_last_name || null},
                    ${profileData.student_first_name || null},
                    ${profileData.student_last_name_kana || null},
                    ${profileData.student_first_name_kana || null},
                    ${profileData.gender || null},
                    ${profileData.birth_date || null},
                    ${profileData.registered_address || null},
                    ${profileData.student_postal_code || null},
                    ${profileData.student_address || null},
                    ${profileData.student_address_detail || null},
                    ${profileData.student_phone || null},
                    ${profileData.middle_school_name || null},
                    ${profileData.graduation_date || null},
                    ${profileData.guardian1_last_name || null},
                    ${profileData.guardian1_first_name || null},
                    ${profileData.guardian1_last_name_kana || null},
                    ${profileData.guardian1_first_name_kana || null},
                    ${profileData.guardian1_postal_code || null},
                    ${profileData.guardian1_address || null},
                    ${profileData.guardian1_address_detail || null},
                    ${profileData.guardian1_phone || null},
                    ${profileData.guardian1_relationship || null},
                    ${profileData.guardian1_relationship_other || null},
                    ${profileData.guardian1_email || null},
                    ${profileData.guardian1_workplace_name || null},
                    ${profileData.guardian1_workplace_postal_code || null},
                    ${profileData.guardian1_workplace_address || null},
                    ${profileData.guardian1_workplace_address_detail || null},
                    ${profileData.guardian1_workplace_phone || null},
                    ${profileData.guardian2_last_name || null},
                    ${profileData.guardian2_first_name || null},
                    ${profileData.guardian2_last_name_kana || null},
                    ${profileData.guardian2_first_name_kana || null},
                    ${profileData.guardian2_postal_code || null},
                    ${profileData.guardian2_address || null},
                    ${profileData.guardian2_address_detail || null},
                    ${profileData.guardian2_phone || null},
                    ${profileData.guardian2_relationship || null},
                    ${profileData.guardian2_relationship_other || null},
                    ${profileData.guardian2_email || null},
                    ${profileData.document_recipient_last_name || null},
                    ${profileData.document_recipient_first_name || null},
                    ${profileData.document_recipient_postal_code || null},
                    ${profileData.document_recipient_address || null},
                    ${profileData.document_recipient_address_detail || null},
                    ${profileData.emergency1_last_name || null},
                    ${profileData.emergency1_first_name || null},
                    ${profileData.emergency1_phone || null},
                    ${profileData.emergency1_relationship || null},
                    ${profileData.emergency1_relationship_other || null},
                    ${profileData.emergency2_last_name || null},
                    ${profileData.emergency2_first_name || null},
                    ${profileData.emergency2_phone || null},
                    ${profileData.emergency2_relationship || null},
                    ${profileData.emergency2_relationship_other || null},
                    ${profileData.has_siblings_at_school || false},
                    ${profileData.family1_last_name || null},
                    ${profileData.family1_first_name || null},
                    ${profileData.family1_relationship || null},
                    ${profileData.family1_relationship_other || null},
                    ${profileData.family1_birth_date || null},
                    ${profileData.family1_living_status || null},
                    ${profileData.family1_workplace_school || null},
                    ${profileData.family2_last_name || null},
                    ${profileData.family2_first_name || null},
                    ${profileData.family2_relationship || null},
                    ${profileData.family2_relationship_other || null},
                    ${profileData.family2_birth_date || null},
                    ${profileData.family2_living_status || null},
                    ${profileData.family2_workplace_school || null},
                    ${profileData.family3_last_name || null},
                    ${profileData.family3_first_name || null},
                    ${profileData.family3_relationship || null},
                    ${profileData.family3_relationship_other || null},
                    ${profileData.family3_birth_date || null},
                    ${profileData.family3_living_status || null},
                    ${profileData.family3_workplace_school || null},
                    ${profileData.family4_last_name || null},
                    ${profileData.family4_first_name || null},
                    ${profileData.family4_relationship || null},
                    ${profileData.family4_relationship_other || null},
                    ${profileData.family4_birth_date || null},
                    ${profileData.family4_living_status || null},
                    ${profileData.family4_workplace_school || null},
                    ${profileData.family5_last_name || null},
                    ${profileData.family5_first_name || null},
                    ${profileData.family5_relationship || null},
                    ${profileData.family5_relationship_other || null},
                    ${profileData.family5_birth_date || null},
                    ${profileData.family5_living_status || null},
                    ${profileData.family5_workplace_school || null},
                    ${profileData.family6_last_name || null},
                    ${profileData.family6_first_name || null},
                    ${profileData.family6_relationship || null},
                    ${profileData.family6_relationship_other || null},
                    ${profileData.family6_birth_date || null},
                    ${profileData.family6_living_status || null},
                    ${profileData.family6_workplace_school || null},
                    ${profileData.commute_method || null},
                    ${profileData.jr_start || null},
                    ${profileData.jr_end || null},
                    ${profileData.subway_nishin_start || null},
                    ${profileData.subway_nishin_end || null},
                    ${profileData.subway_kaigan_start || null},
                    ${profileData.subway_kaigan_end || null},
                    ${profileData.hankyu_start || null},
                    ${profileData.hankyu_end || null},
                    ${profileData.kobe_electric_start || null},
                    ${profileData.kobe_electric_end || null},
                    ${profileData.hanshin_start || null},
                    ${profileData.hanshin_end || null},
                    ${profileData.sanyo_start || null},
                    ${profileData.sanyo_end || null},
                    ${profileData.kobe_bus_start || null},
                    ${profileData.kobe_bus_end || null},
                    ${profileData.sanyo_bus_start || null},
                    ${profileData.sanyo_bus_end || null},
                    ${profileData.shinhi_bus_start || null},
                    ${profileData.shinhi_bus_end || null},
                    ${profileData.other1_transport || null},
                    ${profileData.other1_start || null},
                    ${profileData.other1_end || null},
                    ${profileData.other2_transport || null},
                    ${profileData.other2_start || null},
                    ${profileData.other2_end || null},
                    ${profileData.via_station || null},
                    ${profileData.art_first_choice || null},
                    ${profileData.art_second_choice || null},
                    ${profileData.has_chronic_illness || false},
                    ${profileData.accommodation_notes || null},
                    ${profileData.family_communication || null},
                    ${profileData.chronic_illness_details || null},
                    ${profileData.personal_info_completed || false},
                    ${profileData.commute_info_completed || false},
                    ${profileData.art_selection_completed || false},
                    ${profileData.health_info_completed || false}
                )
                RETURNING *
            `;
            return NextResponse.json({ 
                success: true, 
                message: 'プロフィールを作成しました',
                profile: result.rows[0]
            });
        }
    } catch (error) {
        console.error('Failed to save profile:', error);
        return NextResponse.json(
            { error: 'プロフィールの保存に失敗しました' },
            { status: 500 }
        );
    }
}

export async function GET() {
    try {
        // まずapplication_typeカラムが存在するかチェック
        const columnCheck = await sql`
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'student_profiles' 
            AND column_name = 'application_type'
        `;
        
        let result;
        if (columnCheck.rows.length > 0) {
            // application_typeカラムが存在する場合
            result = await sql`
                SELECT 
                    sp.*,
                    sr.application_type
                FROM student_profiles sp
                LEFT JOIN student_results sr ON sp.student_id = sr.student_id
                ORDER BY sp.created_at DESC
            `;
        } else {
            // application_typeカラムが存在しない場合
            result = await sql`
                SELECT 
                    sp.*,
                    sr.application_type
                FROM student_profiles sp
                LEFT JOIN student_results sr ON sp.student_id = sr.student_id
                ORDER BY sp.created_at DESC
            `;
        }
        
        return NextResponse.json({ 
            success: true, 
            profiles: result.rows 
        });
    } catch (error) {
        console.error('Failed to fetch profiles:', error);
        return NextResponse.json(
            { error: 'プロフィールの取得に失敗しました' },
            { status: 500 }
        );
    }
}
